Return-Path: <git-owner@kernel.org>
X-Spam-Checker-Version: SpamAssassin 3.4.0 (2014-02-07) on
	aws-us-west-2-korg-lkml-1.web.codeaurora.org
X-Spam-Level: 
X-Spam-Status: No, score=-3.8 required=3.0 tests=BAYES_00,
	HEADER_FROM_DIFFERENT_DOMAINS,MAILING_LIST_MULTI,SPF_HELO_NONE,SPF_PASS,
	URIBL_BLOCKED autolearn=no autolearn_force=no version=3.4.0
Received: from mail.kernel.org (mail.kernel.org [198.145.29.99])
	by smtp.lore.kernel.org (Postfix) with ESMTP id 6422EC433ED
	for <git@archiver.kernel.org>; Sun, 25 Apr 2021 00:04:15 +0000 (UTC)
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.kernel.org (Postfix) with ESMTP id 3DF9961245
	for <git@archiver.kernel.org>; Sun, 25 Apr 2021 00:04:15 +0000 (UTC)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229790AbhDYAEx (ORCPT <rfc822;git@archiver.kernel.org>);
        Sat, 24 Apr 2021 20:04:53 -0400
Received: from mav.lukeshu.com ([104.207.138.63]:36942 "EHLO mav.lukeshu.com"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S229687AbhDYAEw (ORCPT <rfc822;git@vger.kernel.org>);
        Sat, 24 Apr 2021 20:04:52 -0400
Received: from lukeshu-dw-thinkpad (unknown [IPv6:2601:281:8200:26:4e34:88ff:fe48:5521])
        by mav.lukeshu.com (Postfix) with ESMTPSA id 642D580590;
        Sat, 24 Apr 2021 20:04:08 -0400 (EDT)
Date:   Sat, 24 Apr 2021 18:04:07 -0600
Message-ID: <87tunv9qmg.wl-lukeshu@lukeshu.com>
From:   Luke Shumaker <lukeshu@lukeshu.com>
To:     Eric Sunshine <sunshine@sunshineco.com>
Cc:     Luke Shumaker <lukeshu@lukeshu.com>,
        Git List <git@vger.kernel.org>,
        Avery Pennarun <apenwarr@gmail.com>,
        Charles Bailey <cbailey32@bloomberg.net>,
        Danny Lin <danny0838@gmail.com>,
        "David A . Greene" <greened@obbligato.org>,
        David Aguilar <davvid@gmail.com>,
        Jakub Suder <jakub.suder@gmail.com>,
        James Denholm <nod.helm@gmail.com>, Jeff King <peff@peff.net>,
        Jonathan Nieder <jrnieder@gmail.com>,
        Junio C Hamano <gitster@pobox.com>,
        =?UTF-8?B?Tmd1?= =?UTF-8?B?eeG7hW4g?= =?ISO-8859-1?Q?Th=E1i_?=
         =?UTF-8?B?Tmfhu41j?= Duy <pclouds@gmail.com>,
        Roger L Strain <roger.strain@swri.org>,
        Techlive Zheng <techlivezheng@gmail.com>,
        Luke Shumaker <lukeshu@datawire.io>
Subject: Re: [PATCH 27/30] subtree: allow --squash to be used with --rejoin
In-Reply-To: <CAPig+cTdTTq+W-QM3y60621GqqgXiHOueKF_Yk35=bL5p8o9uw@mail.gmail.com>
References: <20210423194230.1388945-1-lukeshu@lukeshu.com>
        <20210423194230.1388945-28-lukeshu@lukeshu.com>
        <CAPig+cTdTTq+W-QM3y60621GqqgXiHOueKF_Yk35=bL5p8o9uw@mail.gmail.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM-LB/1.14.9 (=?ISO-8859-4?Q?Goj=F2?=) APEL-LB/10.8 EasyPG/1.0.0
 Emacs/27.2 (x86_64-pc-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
Precedence: bulk
List-ID: <git.vger.kernel.org>
X-Mailing-List: git@vger.kernel.org

On Fri, 23 Apr 2021 23:50:08 -0600,
Eric Sunshine wrote:
> On Fri, Apr 23, 2021 at 3:43 PM Luke Shumaker <lukeshu@lukeshu.com> wrote:
> > +               ! git merge-base --is-ancestor $SUB HEAD &&
> > +               ! git merge-base --is-ancestor $SPLIT HEAD &&
> 
> It's preferable to use `test_must_fail` rather than `!` for Git
> commands

Indeed, this was an oversight on my part.  I'll adjust it.

-- 
Happy hacking,
~ Luke Shumaker
