From: Matthieu Moy <Matthieu.Moy@grenoble-inp.fr>
Subject: Re: [PATCH 5/8] Doc: separate gitignore pattern sources
Date: Sun, 16 Sep 2012 14:03:14 +0200
Message-ID: <vpqzk4qyy2l.fsf@grenoble-inp.fr>
References: <1347793083-4136-6-git-send-email-philipoakley@iee.org>
Mime-Version: 1.0
Content-Type: text/plain
Cc: gitList <git@vger.kernel.org>
To: Philip Oakley <philipoakley@iee.org>
X-From: git-owner@vger.kernel.org Sun Sep 16 14:03:27 2012
Return-path: <git-owner@vger.kernel.org>
Envelope-to: gcvg-git-2@plane.gmane.org
Received: from vger.kernel.org ([209.132.180.67])
	by plane.gmane.org with esmtp (Exim 4.69)
	(envelope-from <git-owner@vger.kernel.org>)
	id 1TDDZP-0005fn-Ec
	for gcvg-git-2@plane.gmane.org; Sun, 16 Sep 2012 14:03:27 +0200
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
	id S1752398Ab2IPMDT (ORCPT <rfc822;gcvg-git-2@m.gmane.org>);
	Sun, 16 Sep 2012 08:03:19 -0400
Received: from mx2.imag.fr ([129.88.30.17]:42343 "EHLO rominette.imag.fr"
	rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
	id S1752375Ab2IPMDT (ORCPT <rfc822;git@vger.kernel.org>);
	Sun, 16 Sep 2012 08:03:19 -0400
Received: from mail-veri.imag.fr (mail-veri.imag.fr [129.88.43.52])
	by rominette.imag.fr (8.13.8/8.13.8) with ESMTP id q8GBvtKm006946
	(version=TLSv1/SSLv3 cipher=AES256-SHA bits=256 verify=NO);
	Sun, 16 Sep 2012 13:57:55 +0200
Received: from anie.imag.fr ([129.88.7.32] helo=anie)
	by mail-veri.imag.fr with esmtps (TLS1.0:DHE_RSA_AES_128_CBC_SHA1:16)
	(Exim 4.72)
	(envelope-from <Matthieu.Moy@grenoble-inp.fr>)
	id 1TDDZC-0001Ec-FP; Sun, 16 Sep 2012 14:03:14 +0200
In-Reply-To: <1347793083-4136-6-git-send-email-philipoakley@iee.org> (Philip
	Oakley's message of "Sun, 16 Sep 2012 11:58:00 +0100")
User-Agent: Gnus/5.13 (Gnus v5.13) Emacs/24.1 (gnu/linux)
X-Greylist: Sender IP whitelisted, not delayed by milter-greylist-4.2.2 (rominette.imag.fr [129.88.30.17]); Sun, 16 Sep 2012 13:57:55 +0200 (CEST)
X-IMAG-MailScanner-Information: Please contact MI2S MIM  for more information
X-MailScanner-ID: q8GBvtKm006946
X-IMAG-MailScanner: Found to be clean
X-IMAG-MailScanner-SpamCheck: 
X-IMAG-MailScanner-From: matthieu.moy@grenoble-inp.fr
MailScanner-NULL-Check: 1348401476.3566@YooytlIE1ZbGlY+igXTOmg
Sender: git-owner@vger.kernel.org
Precedence: bulk
List-ID: <git.vger.kernel.org>
X-Mailing-List: git@vger.kernel.org
Archived-At: <http://permalink.gmane.org/gmane.comp.version-control.git/205609>

Philip Oakley <philipoakley@iee.org> writes:

> + * Patterns which a user wants git to
> +   gnore in all situations (e.g., backup or temporary files generated by

to _i_gnore (missing i).

-- 
Matthieu Moy
http://www-verimag.imag.fr/~moy/
